language: python
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: dG7+G4Aq6jq2fkFqkvJLP2I7JWmdleIIOVc7HMlOXqq9s00EPODPVf5ZqZDaKa0P0nErFcFuYhTJTA0TQRg8YeldyRoupPvdjxaXd3m2/ZZ5HRweBb9SXlaa9PzL/enzUFFpi0sD5wA29oOGjtMh3uo82aEh0gKVI5DcyR18aN/GvSSlMLDcx845ZvJ5wj60dRZuSKHheBeoUIk0v3gcl+j1TpY4Zp+rIfokGu/w6oGa7rHlJgd3SQANR42tQ35ZcrQSYG0JIp8n26TRPZc0Qo9tEe4KB3unY3vF0QgtKfVxyHwsIMOZUv3dVje2XOhon9U6+fB3Z4a1/tPCCVIWtt8I2t/cCKflmGrREHgrG0xxzPk8rIlBB1b/RAOX1yDDX2kiKYSeOJV2RAijZ8S7Ojedx6f921SHBTv8Im+VQ9UsuWDWB3eViJ4+e069oOkA91ioxSj8AMRIwJcJlmelYGPjaI59Qa1VffhzaUfy3itk31xdPtOG+fAFZ7tsHI5AMo3AcoBxT6c9V+pQDu5NBLJHo6n9N+HpjCDYFpaj9Uvq0oPKTAhv6vHxzLd5hQryJzU2BPGizs+NQpNXSvWq/pzsYN5McYl4ZFOz3ww0AqVaQ4RuNxh7+Qeww4lLI5KhoK0fL72nnYiJgm5nOIyWh8Ov2OeyasaXIPjncO1rxZY=
