language: python
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: dG7+G4Aq6jq2fkFqkvJLP2I7JWmdleIIOVc7HMlOXqq9s00EPODPVf5ZqZDaKa0P0nErFcFuYhTJTA0TQRg8YeldyRoupPvdjxaXd3m2/ZZ5HRweBb9SXlaa9PzL/enzUFFpi0sD5wA29oOGjtMh3uo82aEh0gKVI5DcyR18aN/GvSSlMLDcx845ZvJ5wj60dRZuSKHheBeoUIk0v3gcl+j1TpY4Zp+rIfokGu/w6oGa7rHlJgd3SQANR42tQ35ZcrQSYG0JIp8n26TRPZc0Qo9tEe4KB3unY3vF0QgtKfVxyHwsIMOZUv3dVje2XOhon9U6+fB3Z4a1/tPCCVIWtt8I2t/cCKflmGrREHgrG0xxzPk8rIlBB1b/RAOX1yDDX2kiKYSeOJV2RAijZ8S7Ojedx6f921SHBTv8Im+VQ9UsuWDWB3eViJ4+e069oOkA91ioxSj8AMRIwJcJlmelYGPjaI59Qa1VffhzaUfy3itk31xdPtOG+fAFZ7tsHI5AMo3AcoBxT6c9V+pQDu5NBLJHo6n9N+HpjCDYFpaj9Uvq0oPKTAhv6vHxzLd5hQryJzU2BPGizs+NQpNXSvWq/pzsYN5McYl4ZFOz3ww0AqVaQ4RuNxh7+Qeww4lLI5KhoK0fL72nnYiJgm5nOIyWh8Ov2OeyasaXIPjncO1rxZY=
notifications:
  slack:
    secure: UkFxVCfTA0b5hMPfAyX+1EcW8E/X38xu0GuIYvk1HPxxzKbHK07pyw98Ku/XhNfAubt3YhYWoFvSXtYsy7lF4sCcvGmeCOyeCqebZOu4VkAYRHnW1RMZocqShbcMuIGRcu0+0MLF3diaolZC7Zo4IPnGgrbFiA1+1/JmxJQ/+saUdqUkP0dgUZyhv50W8hLHS+n6Gl/ruN/VoNvukekY3GVq5/eUjoNw42JEh5fs5vW+UVYGGsJcVj6tPZkkjpBhuC93Cka8eLDdXvL4fjFWahQJR7tSB9Mhr0cN/BbPLxPXJvuOMRQnCg8/TvnsJbUQCMfwy63eih/hb2Lm9lWjYpBUCT2tOxtqcmPpk1qibaYiI5Zzof2Klqa4m8d+zm2r4VbLjNoo68diadqhkLXllGDnvcKFIR9PwPQI8RqYojCX48zHwowGKXzqWnd0R6MhxfWwPN5gD4pcZaOedT2wWy8CbxnUwfC6cMNMdipsBFDAuYOQXjXrvTP1re3hnXxlsIjRzpORIE05Ap/astl/hNZ3u8YQ20+zlcMAlXoAArGR0rhjo+f5DUv+i/xY4P6d1dCBH92/hYYFDu3edf4y4JarAWRDGZTJZ0OxNvxqCii2gNaBfe8FudsNAtQY53//M2adzoCxaKvkYO99jP5OiPkSN7IHtuYknwDyEwoP8+A=
