name: Tweet
on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tweet
        env:
          SLACK_API_TOKEN: ${{secrets.SLACK_API_TOKEN}}
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
          ACCESS_KEY: ${{secrets.ACCESS_KEY}}
          ACCESS_SECRET: ${{secrets.ACCESS_SECRET}}
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          MASTODON_ACCESS_TOKEN: ${{secrets.MASTODON_ACCESS_TOKEN}}
        run: python src/tweet_progress.py
